blank_issues_enabled: true
contact_links:
  - name: General Question
    url: https://github.com/NewOrleansITI/networkstandards/discussions
    about: Ask questions or start a discussion about network standards
